#配置Server基本属性
server:
  port: 8888
  servlet:
    context-path: /csu_super_mall #配置上下文路径，当前路径为本地路径

#配置JDBC属性
spring:
  datasource:
    url: jdbc:mysql://106.55.173.219:33100/csu_super_mall?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # 更新或者创建数据表结构
      ddl-auto: update
      #jpa对实体类的默认字段会把驼峰命名的属性，转换为字段名的时候自动加上下划线。 这个配置的作用就是去掉下划线
      #比如属性名称是 createDate, jpa 默认转换为字段名 create_Date。 有了这个配置之后，就会转换为同名字段 createDate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # 控制台显示SQL
    show-sql: true